### PR TITLE
Build update to android pie - API 28

### PR DESCRIPTION
**Pull request by Lucem-Anb**
This update fixes common bugs during usage of the project like "unable to merge dex" and "compile is obsolete". Google will drop updates of apps build with Android version earlier than marshmallow this year, thus this update comes in handy.

### CODE REVIEW

**Comment by attenzione** [comment]
Thanks for the update.
Is it necessary to add `.idea` and `Sample` to the repository?

**Comment by Lucem-Anb** [comment]
@attenzione you are welcome, Thank you too.
`.idea` is not very necessary but `Sample` is necessary since I changed the configuration for the module `Sample`. Using the same build version (`compileSdkVersion 28`) is recommended.

**Comment by attenzione** [comment]
> @attenzione you are welcome, Thank you too.
> `.idea` is not very necessary but `Sample` is necessary since I changed the configuration for the module `Sample`. Using the same build version (`compileSdkVersion 28`) is recommended.

I thought completely remove `Sample` from the repository.
Okey, let's remove `.idea` and keep `Sample` for now.

**Comment by Lucem-Anb** [comment]
okay, here's a new commit. 
removed autogenerated files: .idea, .gradle and build folder. This will be generated if the user clones and builds the project on Android studio. 
I think Sample is really helpful, Its the one that gave me interest to the project since it shows how the app works. 😃

**Pull request merged**
